# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "bento/ubuntu-20.04"
  
  # Configure DB machine
  config.vm.define "db" do |db|
    db.vm.network "private_network", ip: "192.168.10.30"
    db.vm.network "forwarded_port", guest: 3306, host: 3306
    db.vm.synced_folder ".", "/vagrant", disabled: true
    db.vm.provider "virtualbox" do |vb|
      vb.name = "db"
      vb.memory = "1024"
      vb.cpus = 1
    end
    db.vm.provision "file", source: "./data/default", destination: "$HOME/nginx-config/"
    db.vm.provision "shell" do |s|
      s.path = "./db-provisioner.sh"
      s.env = { "MYSQL_PASSWORD" => "password", "DB_NAME" => "movie_db", "DB_USER" => "applicationuser", "DB_PASS" => "applicationpass"}      
      s.privileged = false
    end
  end
 
  # Configure API machine
  config.vm.define "api" do |api|
    api.vm.network "private_network", ip: "192.168.10.20"
    api.vm.network "forwarded_port", guest: 80, host: 8081
    api.vm.synced_folder ".", "/vagrant", disabled: true
    api.vm.provider "virtualbox" do |vb|
      vb.name = "api"
      vb.memory = "1024"
      vb.cpus = 1
    end
    api.vm.provision "file", source: "./data/default", destination: "$HOME/nginx-config/"
    api.vm.provision "shell" do |s|
      s.path = "./node-provisioner.sh"
      s.env = { "PROJECT_REPO" => "https://github.com/sagudeloo/movie-analyst-api.git", "PORT" => "3000", "DB_HOST" => "192.168.10.30", "DB_NAME" => "movie_db", "DB_USER" => "applicationuser", "DB_PASS" => "applicationpass"}
      s.privileged = false
    end
    api.vm.provision "shell" do |s|
      s.path = "./db-migrator.sh"
      s.env = { "DB_HOST" => "192.168.10.30", "DB_NAME" => "movie_db", "DB_USER" => "applicationuser", "DB_PASS" => "applicationpass"}
      s.privileged = false
    end
  end
  
  # Configure UI machine
  config.vm.define "ui" do |ui|
    ui.vm.network "private_network", ip: "192.168.10.10"
    ui.vm.network "forwarded_port", guest: 80, host: 8080
    ui.vm.synced_folder ".", "/vagrant", disabled: true
    ui.vm.provider "virtualbox" do |vb|
      vb.name = "ui"
      vb.memory = "1024"
      vb.cpus = 1
    end
    ui.vm.provision "file", source: "./data/default", destination: "$HOME/nginx-config/"
    ui.vm.provision "shell" do |s|
      s.path = "./node-provisioner.sh"
      s.env = { "PROJECT_REPO" => "https://github.com/sagudeloo/movie-analyst-ui.git", "PORT" => "3000", "BACK_HOST" => "192.168.10.20"}  
      s.privileged = false
    end
  end

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
