---
- name: api
  hosts: api
  become: yes
  roles:
    - role: common
      project_repo: https://github.com/sagudeloo/movie-analyst-api.git
      project_name: movie-analyst-api
  environment:
    port: 80
