---
- name: ui
  hosts: ui
  debugger: always
  become: yes
  roles:
    - role: common
      project_repo: https://github.com/sagudeloo/movie-analyst-ui.git
      project_name: movie-analyst-ui
  environment:
    port: 80
    back_host: http://ramp-up-devops.culea.me:8080/
